apiVersion: v1
kind: Service
metadata:
  name: quorum-node
spec:
  selector:
    app: quorum-node
  type: ClusterIP
  clusterIP: 10.100.10.1
  ports:
  - name: peer
    port: 21000
    targetPort: 21000
    protocol: TCP
  - name: peer-udp
    port: 21000
    targetPort: 21000
    protocol: UDP
  - name: rpc
    port: 22000
    targetPort: 8080
  - name: raft
    port: 22003
    targetPort: 22003
  - name: tessera-peer
    port: 9001
    targetPort: 9001
  - name: tessera-third-party
    port: 9081
    targetPort: 9081